import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/components/navbar/nav";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Navbar />
            {children}
            <Toaster />
            <Footer />
        </>
    );
}
